
import React, { useState, useEffect } from 'react';
import { Dashboard } from './components/Dashboard';
import { LessonGenerator } from './components/LessonGenerator';
import { LessonView } from './components/LessonView';
import { Login } from './components/Login';
import { WelcomeScreen } from './components/WelcomeScreen';
import { GamificationHub } from './components/GamificationHub';


import { ProfileView } from './components/ProfileView';
import { InteractiveSimulation } from './components/InteractiveSimulation';
import { SongsStories } from './components/SongsStories';
import { AppView, LessonPlan, UserProfile, Resource, Theme } from './types';
import { SchoolCalendar } from './components/SchoolCalendar';
import { ClassManager } from './components/ClassManager';

import { StoryWeaver } from './components/StoryWeaver';
import { MelodyStudio } from './components/MelodyStudio';
import { PrivateVault } from './components/PrivateVault';
import { CurriculumAgent } from './components/CurriculumAgent';
import { StudentOasis } from './components/StudentOasis';
import { OasisCommandCenter } from './components/OasisCommandCenter';
import { fetchLessonPlans, saveLessonPlan } from './services/syncService';
import { supabase } from './services/supabaseClient';

const App: React.FC = () => {
    const [user, setUser] = useState<UserProfile | null>(null);
    const [currentView, setCurrentView] = useState<AppView>('welcome');
    const [recentPlans, setRecentPlans] = useState<LessonPlan[]>([]);
    const [selectedPlan, setSelectedPlan] = useState<LessonPlan | null>(null);
    const [calendarInitialEvent, setCalendarInitialEvent] = useState<{ title: string; subject?: string; grade?: string; planId?: string } | undefined>(undefined);
    const [currentTheme, setCurrentTheme] = useState<Theme>('default');
    const [lessonGenProps, setLessonGenProps] = useState<{ initialTopic?: string; initialGrade?: string; initialActivities?: string[] }>({});

    // Check active session on mount
    useEffect(() => {
        supabase.auth.getSession().then(({ data: { session } }) => {
            if (session?.user) {
                // Fetch profile
                supabase.from('profiles').select('*').eq('id', session.user.id).single()
                .then(({ data: profile }) => {
                    if (profile) {
                         setUser({
                            id: profile.id,
                            name: profile.full_name,
                            role: profile.role === 'teacher' ? 'معلم صف' : profile.role === 'student' ? 'طالب' : 'ضيف',
                            school: profile.school,
                            subject: profile.subject,
                            bio: profile.bio,
                            themePreference: profile.theme_preference,
                            avatar: profile.avatar_url || `https://api.dicebear.com/7.x/avataaars/svg?seed=${profile.id}`
                        } as UserProfile);
                    }
                });
            }
        });

        // Listen for auth changes
        const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => {
             if (!session) {
                 setUser(null);
                 setCurrentView('welcome');
             }
        });

        return () => subscription.unsubscribe();
    }, []);

    // Sync theme with user profile
    useEffect(() => {
        if (user?.themePreference) {
            setCurrentTheme(user.themePreference);
        }
        
        // Fetch Lesson Plans from Supabase if user is logged in
        if (user && user.role !== 'ضيف') {
            fetchLessonPlans().then(plans => {
                setRecentPlans(plans as LessonPlan[]);
            }).catch(err => console.error("Error fetching plans:", err));
        }
    }, [user]);

    // Apply theme to body
    useEffect(() => {
        document.body.setAttribute('data-theme', currentTheme);
    }, [currentTheme]);

    const handleThemeChange = (newTheme: Theme) => {
        setCurrentTheme(newTheme);
        if (user) {
            // This updates state, which triggers the useEffect above
            handleUpdateUser({ ...user, themePreference: newTheme });
        }
    };

    const handleLogin = (newUser: UserProfile) => {
        setUser(newUser);
        
        if (newUser.role === 'طالب') {
            setCurrentView('student-oasis');
        } else {
            setCurrentView('dashboard');
        }

        // --- AUTOMATIC LESSON GENERATION (FROM PDF DATA) ---
        // Only generate for new logins if list is empty
        if (recentPlans.length === 0 && newUser.role !== 'طالب' && newUser.role !== 'ضيف') {
             const autoGeneratedLesson: LessonPlan = {
                id: `auto-${Date.now()}`,
                topic: "الماء في حياتنا",
                subject: "العلوم",
                grade: "الصف الثاني", // Matches PDF
                teacherName: newUser.name,
                date: "2026-02-14", // Matches PDF
                resources: "الكتاب المدرسي، صور توضيحية، أوراق عمل", // Matches PDF

                // Objectives - Mapped from PDF 'general_outcomes' and 'learning_outcomes'
                objectives: [
                    { domain: 'cognitive', text: "أن يتذكر الطالب معلوماته السابقة عن الموضوع." },
                    { domain: 'cognitive', text: "أن يتذكر الطالب المفاهيم الأساسية." },
                    { domain: 'skill', text: "أن يستكشف الطالب المفاهيم الجديدة." },
                    { domain: 'skill', text: "أن يطبق الطالب ما تعلمه." }
                ],

                // Prerequisites - From 'introduction'
                prerequisites: [
                    "عرض صورة متعلقة بـ الماء في حياتنا",
                    "طرح سؤال تحفيزي"
                ],

                // Procedures Matrix - From 'lesson_phases'
                procedures: [
                    {
                        step: "التهيئة والاستكشاف",
                        teacherRole: "يطرح أسئلة تحفيزية ويشجع المشاركة.",
                        studentRole: "يفكر ويشارك بناءً على خبرته.",
                        strategy: "عصف ذهني / نقاش مفتوح",
                        time: "5 د"
                    },
                    {
                        step: "الاستكشاف والتطبيق",
                        teacherRole: "يوجه الأنشطة ويقدم الدعم.",
                        studentRole: "يعمل في مجموعات لاستكشاف المحتوى.",
                        strategy: "تعلم تعاوني / أنشطة جماعية تفاعلية",
                        time: "15 د"
                    },
                    {
                        step: "التثبيت والممارسة",
                        teacherRole: "يشرف على التطبيق الفردي.",
                        studentRole: "يحل تمارين فردية.",
                        strategy: "عمل فردي / تمارين تطبيقية",
                        time: "15 د"
                    }
                ],

                // Evaluation Questions - From 'assessment' sections
                evaluationQuestions: [
                    "ماذا تعرف عن هذا الموضوع؟",
                    "ماذا اكتشفت؟",
                    "هل أتقنت المهارة؟",
                    "ماذا تعلمنا اليوم؟"
                ],

                // Closure - From 'closure'
                closureActivity: "تلخيص جماعي للدرس عبر خريطة ذهنية.",

                // Differentiation - From 'differentiation'
                differentiation: {
                    enrichment: "بحث إضافي وتصميم مشروع صغير (مهارات البحث والإبداع).",
                    support: "أنشطة مبسطة مع دعم إضافي (التركيز على المهارات الأساسية)."
                },

                // Reflection - From 'reflection'
                reflection: {
                    teacherNotes: "الدرس تفاعلي والطلاب متحمسون.",
                    strengths: "التنوع في الأنشطة، مشاركة الطلاب الفعالة.",
                    weaknesses: "تخصيص وقت أكثر للتطبيق الفردي."
                },

                // Smart Guide (Inferred)
                smartGuide: {
                    valueAdded: "تعزيز الوعي البيئي وأهمية الماء في الحياة (مهارات حياتية).",
                    smartTool: "استخدام تطبيق تفاعلي لدورة المياه في الطبيعة."
                },

                // Slides & Scenario (Constructed to align with the phases)
                slides: [
                    {
                        slideNumber: 1,
                        title: "الماء في حياتنا",
                        narration: `السيناريو: أهلاً بكم يا علماء المستقبل! اليوم سنتحدث عن سر الحياة. انظروا حولكم، أين نجد الماء؟ وكيف نستخدمه؟`,
                        visualDescription: "3D Disney style animation of a vibrant classroom with a large water drop character on the smartboard. Bright lighting.",
                        duration: 1
                    },
                    {
                        slideNumber: 2,
                        title: "ماذا نعرف؟ (عصف ذهني)",
                        narration: `السيناريو: سأعرض عليكم صورة. ماذا ترون؟ هل الماء ضروري للنباتات فقط؟ أم للإنسان والحيوان أيضاً؟`,
                        visualDescription: "Illustration showing a collage of water uses: drinking, rain, rivers, washing. Colorful and engaging style.",
                        duration: 5
                    },
                    {
                        slideNumber: 3,
                        title: "مرحلة الاستكشاف (عمل مجموعات)",
                        narration: `السيناريو: الآن في مجموعاتكم، لديكم صور وأدوات. أريد منكم استكشاف حالات الماء. هل هو سائل دائماً؟`,
                        visualDescription: "Students working in small groups around tables with magnifying glasses and water containers. 3D Pixar style.",
                        duration: 8
                    },
                    {
                        slideNumber: 4,
                        title: "مشاركة الاكتشافات",
                        narration: `السيناريو: لنتشارك ما اكتشفناه. المجموعة الأولى، ماذا وجدتم؟ (نقاش تفاعلي).`,
                        visualDescription: "A student standing up presenting a drawing to the class while others listen attentively.",
                        duration: 7
                    },
                    {
                        slideNumber: 5,
                        title: "تطبيق ما تعلمناه",
                        narration: `السيناريو: جاء وقت التحدي الفردي! افتحوا أوراق العمل. صل بين الصورة والكلمة المناسبة.`,
                        visualDescription: "Close up of a worksheet about water with a pencil. Focus on the student's hand writing.",
                        duration: 10
                    },
                    {
                        slideNumber: 6,
                        title: "المبدع الصغير (تمايز)",
                        narration: `السيناريو: من أنهى الحل، يمكنه البدء في تصميم مشروع صغير: "كيف نوفر الماء في المدرسة؟"`,
                        visualDescription: "A thought bubble showing a student imagining a water-saving invention. Creative and dreamy style.",
                        duration: 5
                    },
                    {
                        slideNumber: 7,
                        title: "خريطة المفاهيم (الخاتمة)",
                        narration: `السيناريو: لنلخص درسنا اليوم في خريطة ذهنية جميلة. الماء: مصدره، فوائده، وطرق الحفاظ عليه.`,
                        visualDescription: "A large colorful mind map on a smartboard with 'Water' in the center and branches showing its uses.",
                        duration: 4
                    }
                ]
            };

            setRecentPlans([autoGeneratedLesson, ...recentPlans]);
        }
    };

    const handleUpdateUser = async (updatedUser: UserProfile) => {
        setUser(updatedUser);
        
        // Sync to Supabase Profiles
        try {
            const { data: { user: authUser } } = await supabase.auth.getUser();
            if (authUser) {
                const { error } = await supabase
                    .from('profiles')
                    .update({
                        full_name: updatedUser.name,
                        school: updatedUser.school,
                        subject: updatedUser.subject,
                        bio: updatedUser.bio,
                        // role is usually fixed, but we can update if needed
                        theme_preference: updatedUser.themePreference || 'default',
                        // stats might need a separate table or column if JSONB
                    })
                    .eq('id', authUser.id);
                
                if (error) console.error("Failed to sync profile:", error);
            }
        } catch (e) {
            console.error("Profile sync error:", e);
        }
    };

    const handleGuestAccess = () => {
        const guestUser: UserProfile = {
            name: "زائر للنظام",
            role: "ضيف",
            school: "وصول عام (Public Access)"
        };
        setUser(guestUser);
        // We DO NOT save to localStorage so the guest session is temporary
        setCurrentView('dashboard');
    };


    const handleLogout = () => {
        supabase.auth.signOut().then(() => {
            setUser(null);
            setCurrentView('welcome');
        });
    };

    const handleLessonGenerated = (plan: LessonPlan) => {
        setRecentPlans([plan, ...recentPlans]);
        setSelectedPlan(plan);
        setCurrentView('view-lesson');
    };

    const handleSaveLesson = async (plan: LessonPlan) => {
        try {
            // Save to Supabase
            const savedPlan = await saveLessonPlan(plan);
            
            // Update local state by replacing old plan (by old ID) with new plan (new ID)
            setRecentPlans(prev => {
                const index = prev.findIndex(p => p.id === plan.id);
                if (index !== -1) {
                    const newPlans = [...prev];
                    newPlans[index] = savedPlan as LessonPlan;
                    return newPlans;
                } else {
                    return [savedPlan as LessonPlan, ...prev];
                }
            });

            // Also update selected plan if it's the one we just saved
            if (selectedPlan && selectedPlan.id === plan.id) {
                setSelectedPlan(savedPlan as LessonPlan);
            }

            alert('✅ تم حفظ الدرس بنجاح!');
        } catch (e) {
            console.error('Failed to save lesson:', e);
            alert('حدث خطأ أثناء الحفظ. يرجى المحاولة مرة أخرى.');
        }
    };

    const renderView = () => {
        switch (currentView) {
            case 'welcome':
                return (
                    <WelcomeScreen
                        onStartLogin={() => setCurrentView('login-teacher')}
                        onStudentLogin={() => setCurrentView('login-student')}
                        onGuestAccess={handleGuestAccess}
                    />
                );
            case 'login-teacher':
                return <Login onLogin={(u) => handleLogin({ ...u, role: u.role || 'معلم صف' })} userType="teacher" onBack={() => setCurrentView('welcome')} />;
            case 'login-student':
                return <Login onLogin={(u) => handleLogin({ ...u, role: 'طالب' })} userType="student" onBack={() => setCurrentView('welcome')} />;
            case 'dashboard':
                return user ? (
                    <Dashboard
                        user={user}
                        recentPlans={recentPlans}
                        onNewLesson={() => setCurrentView('create-lesson')}
                        onViewLesson={(plan) => {
                            setSelectedPlan(plan);
                            setCurrentView('view-lesson');
                        }}
                        onGamification={() => setCurrentView('gamification')}
                        onSimulation={() => setCurrentView('simulation')}
                        onSongs={() => setCurrentView('songs')}
                        onCalendar={() => { setCalendarInitialEvent(undefined); setCurrentView('calendar'); }}
                        onClassManager={() => setCurrentView('class-manager')}
                        onProfile={() => setCurrentView('profile')}
                        onLogout={handleLogout}
                        currentTheme={currentTheme}
                        onThemeChange={(theme) => setUser({ ...user, theme })}
                        onStoryWeaver={() => setCurrentView('story-weaver')}
                        onMelodyStudio={() => setCurrentView('melody-studio')}
                        onPrivateVault={() => setCurrentView('private-vault')}
                        onCurriculumAgent={() => setCurrentView('curriculum-agent')}
                        onStudentOasis={() => setCurrentView('student-oasis')}
                        onOasisCommandCenter={() => setCurrentView('oasis-command-center')}
                    />
                ) : <WelcomeScreen onStartLogin={() => setCurrentView('login-teacher')} onGuestAccess={handleGuestAccess} />;
            case 'create-lesson':
                return (
                    <LessonGenerator
                        onSuccess={handleLessonGenerated}
                        onCancel={() => setCurrentView('dashboard')}
                        initialTopic={lessonGenProps.initialTopic}
                        initialGrade={lessonGenProps.initialGrade}
                        initialActivities={lessonGenProps.initialActivities}
                    />
                );
            case 'view-lesson':
                return selectedPlan ? (
                    <LessonView
                        plan={selectedPlan}
                        onBack={() => setCurrentView('dashboard')}
                        onGamification={() => setCurrentView('gamification')}
                        onSimulation={() => setCurrentView('simulation')}
                        onSongs={() => setCurrentView('songs')}
                        onSave={handleSaveLesson}
                        onSchedule={() => {
                            setCalendarInitialEvent({
                                title: selectedPlan!.topic,
                                subject: selectedPlan!.subject,
                                grade: selectedPlan!.grade,
                                planId: selectedPlan!.id,
                            });
                            setCurrentView('calendar');
                        }}
                    />
                ) : null;
            case 'story-weaver':
                return <StoryWeaver onBack={() => setCurrentView('dashboard')} />;
            case 'melody-studio':
                return <MelodyStudio onBack={() => setCurrentView('dashboard')} />;
            case 'gamification':
                return selectedPlan ? (
                    <GamificationHub
                        onBack={() => setCurrentView('dashboard')}
                        initialTopic={selectedPlan.topic}
                        initialGrade={selectedPlan.grade}
                    />
                ) : (
                    <GamificationHub
                        onBack={() => setCurrentView('dashboard')}
                    />
                );
            case 'simulation':
                return selectedPlan ? (
                    <InteractiveSimulation
                        onBack={() => setCurrentView('dashboard')}
                        initialTopic={selectedPlan.topic}
                        initialSubject={selectedPlan.subject}
                    />
                ) : (
                    <InteractiveSimulation
                        onBack={() => setCurrentView('dashboard')}
                    />
                );
            case 'songs':
                return selectedPlan ? (
                    <SongsStories
                        onBack={() => setCurrentView('dashboard')}
                        initialTopic={selectedPlan.topic}
                        initialGrade={selectedPlan.grade}
                    />
                ) : (
                    <SongsStories
                        onBack={() => setCurrentView('dashboard')}
                    />
                );
            case 'profile':
                return user ? (
                    <ProfileView
                        user={user}
                        onUpdateUser={handleUpdateUser}
                        onBack={() => setCurrentView('dashboard')}
                    />
                ) : null;
            case 'calendar':
                return (
                    <SchoolCalendar
                        onBack={() => setCurrentView('dashboard')}
                        initialEvent={calendarInitialEvent}
                    />
                );
            case 'class-manager':
                return (
                    <ClassManager
                        onBack={() => setCurrentView('dashboard')}
                        onNewLesson={() => setCurrentView('create-lesson')}
                        onViewLesson={(plan: LessonPlan) => {
                            setSelectedPlan(plan);
                            setCurrentView('view-lesson');
                        }}
                    />
                );
            case 'private-vault':
                return <PrivateVault onBack={() => setCurrentView('dashboard')} />;
            case 'curriculum-agent':
                return (
                    <CurriculumAgent 
                        onBack={() => setCurrentView('dashboard')} 
                        onGenerateLesson={(topic, grade, activities) => {
                            setLessonGenProps({ initialTopic: topic, initialGrade: grade, initialActivities: activities });
                            setCurrentView('create-lesson');
                        }}
                    />
                );
            case 'student-oasis':
                return (
                    <StudentOasis 
                        onBack={() => {
                            if (user?.role === 'طالب') {
                                handleLogout();
                            } else {
                                setCurrentView('dashboard');
                            }
                        }}
                        userParams={{ name: user?.name.split(' ')[0] || 'بطل', grade: 'الرابع' }}
                        isTeacherMode={user?.role !== 'طالب'}
                    />
                );
            case 'oasis-command-center':
                return (
                    <OasisCommandCenter 
                        currentLesson={selectedPlan || undefined}
                        onBack={() => setCurrentView('dashboard')} 
                    />
                );
            default:
                return <div>System Error: View Not Found</div>;
        }
    };

    return (
        <div className="min-h-screen font-sans text-slate-100 bg-slate-950" dir="rtl">
            <main className="w-full h-full min-h-screen">
                {renderView()}
            </main>
        </div>
    );
};

export default App;
