-- تشغيل هذا الكود في Supabase -> SQL Editor
-- Run this code in Supabase -> SQL Editor

-- 1. تفريغ الجداول القديمة (اختياري - احذر حذف البيانات)
-- drop table if exists profiles cascade;
-- drop table if exists student_progress cascade;
-- drop table if exists chat_history cascade;
-- drop table if exists teacher_broadcasts cascade;

-- 2. جدول المستخدمين (مرتبط بـ Supabase Auth)
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text check (role in ('teacher', 'student')),
  school text,
  phone text,
  
  -- Game Stats (Students)
  xp integer default 0,
  level integer default 1,
  badges text[] default '{}',
  
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- دالة لإنشاء بروفايل تلقائياً عند تسجيل مستخدم جديد
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, role, school, phone)
  values (
    new.id, 
    new.raw_user_meta_data->>'full_name', 
    new.raw_user_meta_data->>'role', 
    new.raw_user_meta_data->>'school',
    new.raw_user_meta_data->>'phone'
  );
  return new;
end;
$$ language plpgsql security definer;

-- تفعيل الدالة (Trigger)
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 3. باقي الجداول (تقدم، محادثات)
create table if not exists student_progress (
  id bigint generated by default as identity primary key,
  student_id uuid references profiles(id),
  lesson_title text not null,
  unlocked_at timestamp with time zone default timezone('utc'::text, now()),
  unique(student_id, lesson_title)
);

create table if not exists chat_history (
  id bigint generated by default as identity primary key,
  student_id uuid references profiles(id),
  sender text not null, 
  text text not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists teacher_broadcasts (
  id bigint generated by default as identity primary key,
  teacher_id uuid references profiles(id),
  message text,
  type text, 
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. إعدادات Realtime
alter publication supabase_realtime add table profiles;
alter publication supabase_realtime add table student_progress;
alter publication supabase_realtime add table chat_history;
alter publication supabase_realtime add table teacher_broadcasts;

-- 5. سياسات الأمان (RLS)
alter table profiles enable row level security;
create policy "Public Profile Access" on profiles for select using (true);
create policy "User Update Own Profile" on profiles for update using (auth.uid() = id);

alter table student_progress enable row level security;
create policy "Student Own Progress" on student_progress for all using (auth.uid() = student_id);

alter table chat_history enable row level security;
create policy "Student Own Chat" on chat_history for all using (auth.uid() = student_id);

alter table teacher_broadcasts enable row level security;
create policy "Teachers Broadcast" on teacher_broadcasts for insert with check (exists (select 1 from profiles where id = auth.uid() and role = 'teacher'));
create policy "Everyone Read Broadcasts" on teacher_broadcasts for select using (true);
