-- تشغيل هذا الكود في Supabase -> SQL Editor
-- Run this code in Supabase -> SQL Editor

-- 1. جدول الفصول الدراسية (Classes)
-- نستخدم UUID لتجنب مشاكل التعارض إذا كان الجدول موجوداً مسبقاً بنوع مختلف
create table if not exists classes (
  id uuid default gen_random_uuid() primary key,
  teacher_id uuid references profiles(id) on delete cascade,
  grade text not null,      -- الصف (مثلاً: الرابع)
  section text not null,    -- الشعبة (مثلاً: الأولى)
  subject text,             -- المادة (اختياري)
  class_code text unique not null, -- كود الانضمام الفريد (مثلاً: AB123)
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. جدول انضمام الطلاب للفصول (Enrollments)
create table if not exists class_enrollments (
  id bigint generated by default as identity primary key,
  class_id uuid references classes(id) on delete cascade,
  student_id uuid references profiles(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(class_id, student_id)
);

-- 3. تحديث جدول الملفات الشخصية (Profiles) لإضافة حقل كود الفصل (اختياري للراحة)
alter table profiles add column if not exists current_class_code text;

-- 4. سياسات الأمان (RLS)
alter table classes enable row level security;
create policy "Teachers create classes" on classes for insert with check (auth.uid() = teacher_id);
create policy "Teachers view own classes" on classes for select using (auth.uid() = teacher_id);
create policy "Students view classes by code" on classes for select using (true); -- للسماح بالبحث عن الكود

alter table class_enrollments enable row level security;
create policy "Teachers manage enrollments" on class_enrollments for all using (
  exists (select 1 from classes where id = class_enrollments.class_id and teacher_id = auth.uid())
);
create policy "Students join classes" on class_enrollments for insert with check (auth.uid() = student_id);
create policy "Students view own enrollments" on class_enrollments for select using (auth.uid() = student_id);
